{"name": "test_run", "status": "failed", "statusDetails": {"message": "AssertionError: Adding user process is failed\nassert 'Successfully Saved' == ''\n  \n  + Successfully Saved", "trace": "self = <test.test_runner.Test object at 0x000002B7C195E7E0>\n\n    def test_run(self):\n    \n        login_logout = LoginLogout(self.driver)\n        user_management = login_logout.login()\n        user_management.click_admin()\n        user_management.system_user_verification(self.system_users)\n        user_management.add_user_btn()\n>       user_management.add_user_credentials(self.emp_name, self.user_input, self.input_pw, self.input_confirm_pw,\n                                             self.added_user_step_name, self.added_user_screenshot_name,\n                                             self.expected_add_user_success_msg)\n\ntest_runner.py:17: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <page_objects.test_user_management.User object at 0x000002B7C1908FE0>, emp_name = 'a', user_input = 'Dhanraj123'\ninput_pw = 'Manju@2522', input_confirm_pw = 'Manju@2522', added_user_step_name = 'user added'\nadded_user_screenshot_name = 'Successfully added user', expected_add_user_success_msg = 'Successfully Saved'\n\n    def add_user_credentials(self, emp_name, user_input, input_pw, input_confirm_pw, added_user_step_name,\n                             added_user_screenshot_name, expected_add_user_success_msg):\n        form = self.wait_until_visibility_element_located(self.switch_to_add_user_form)\n        UserRoleDropdown = form.find_element(*self.user_role_dropdown)\n        UserRoleDropdown.click()\n        ClickAdminOption = form.find_element(*self.click_admin_option)\n        ClickAdminOption.click()\n        StatusDropdown = form.find_element(*self.status_dropdown)\n        StatusDropdown.click()\n        ClickEnabledOPtion = form.find_element(*self.click_enabled_option)\n        ClickEnabledOPtion.click()\n        self.send_keys_to_element(self.employee_name, emp_name)\n        self.click_on_element(self.employee_option)\n        self.send_keys_to_element(self.username, user_input)\n        self.send_keys_to_element(self.pw, input_pw)\n        self.send_keys_to_element(self.confirm_pw, input_confirm_pw)\n        self.click_on_element(self.save_btn)\n        actual_success_msg = self.driver.find_element(*self.Saved_msg).text\n>       assert expected_add_user_success_msg == actual_success_msg.strip(), \"Adding user process is failed\"\nE       AssertionError: Adding user process is failed\nE       assert 'Successfully Saved' == ''\nE         \nE         + Successfully Saved\n\n..\\page_objects\\test_user_management.py:46: AssertionError"}, "start": 1724843971590, "stop": 1724843980781, "uuid": "23c960d8-899d-47cb-ab2c-fdd31121afd1", "historyId": "fbda50be7b9b9a0d0ef3f37d4cb58701", "testCaseId": "fbda50be7b9b9a0d0ef3f37d4cb58701", "fullName": "test_runner.Test#test_run", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "suite", "value": "test_runner"}, {"name": "subSuite", "value": "Test"}, {"name": "host", "value": "LAPTOP-1L6QCUMU"}, {"name": "thread", "value": "20500-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_runner"}]}